### ISSUE TITLE
add a new configuration to set default image registry in bc-apis

### ISSUE THREAD

**Issue by bjwswang** [bestchains/installer#16]

**Comment by bjwswang** [comment]
@dayuy please provide the environment name

**Comment by dayuy** [comment]
deploy/bff-api 需要增加两个环境变量：IMAGE_NAMESPACE、IMAGE_FABRIC_CA_TAG，
![20230216144043](https://user-images.githubusercontent.com/17400942/219288027-70f829e3-13c8-4d02-b70c-22a7fac8416b.jpg)
