### ISSUE TITLE
sync webhooks from fabric-operator

### ISSUE THREAD

**Issue by bjwswang** [bestchains/installer#4]

**Comment by bjwswang** [comment]
@0xff-dev please update webhooks 
- https://github.com/0xff-dev/installer/blob/main/fabric-operator/templates/mutatingwebhook.yaml
- https://github.com/0xff-dev/installer/blob/main/fabric-operator/templates/validatingwebhook.yaml

**Comment by 0xff-dev** [comment]
https://github.com/bestchains/installer/pull/2/files#diff-743c6096447be3968cee9de4a5b4499a73105a126a178dad37b869d10de8fe0fR14
