### ISSUE TITLE
docker-build Task support auth authentication

### ISSUE THREAD

**Issue by Abirdcfly** [bestchains/installer#44]
docker-build Task now not support auth authentication.

In reality, unless the registry is within the cluster, there will almost certainly be an authentication process for the registry.

Should we make it support auth authentication? And what is the priority of this task?

cc @bjwswang

**Comment by bjwswang** [comment]
docker-build task can be deprecated. only `kaniko-task` reversved

**Comment by Abirdcfly** [comment]
As we only maintain `kaniko-task`, we will close the current issue.
